# Generated by Django 4.1.5 on 2023-01-10 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_taskrating_task_task_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_rating',
            new_name='rating',
        ),
    ]
