# Generated by Django 4.1.5 on 2023-01-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_rename_task_rating_task_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='rating',
            field=models.ManyToManyField(blank=True, to='task.taskrating'),
        ),
    ]
